"""Markdown report generator."""

import json
from datetime import datetime
from typing import Any, Dict


class MarkdownReporter:
    """Generate Markdown reports from analysis results."""
    
    def __init__(self):
        self.template = """# Predictive Linguistics Report
Generated: {timestamp}

## Emerging Metaphors
{metaphors}

## Archetypes
{archetypes}

## Emotional Spikes
{emotional_spikes}

## Contradictions
{contradictions}

## Future Leak Indicators
{future_leaks}

---
*Generated by Predictive Linguistics WebBot*
"""
    
    def generate(self, data: Dict[str, Any]) -> str:
        """Generate Markdown report."""
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        
        metaphors = self._format_metaphors(data.get("metaphors", []))
        archetypes = self._format_archetypes(data.get("archetypes", []))
        emotional_spikes = self._format_emotional_spikes(data.get("emotional_spikes", []))
        contradictions = self._format_contradictions(data.get("contradictions", []))
        future_leaks = self._format_future_leaks(data.get("future_leaks", []))
        
        return self.template.format(
            timestamp=timestamp,
            metaphors=metaphors,
            archetypes=archetypes,
            emotional_spikes=emotional_spikes,
            contradictions=contradictions,
            future_leaks=future_leaks
        )
    
    def _format_metaphors(self, metaphors: list) -> str:
        if not metaphors:
            return "No emerging metaphors detected."
        
        lines = []
        for m in metaphors:
            lines.append(f"- **{m.get('term', 'N/A')}**: {m.get('context', '')} (spread: {m.get('spread_score', 0):.2f})")
        return "\n".join(lines)
    
    def _format_archetypes(self, archetypes: list) -> str:
        if not archetypes:
            return "No archetypes detected."
        
        lines = []
        for a in archetypes:
            lines.append(f"- **{a.get('name', 'N/A')}**: {a.get('description', '')} (freq: {a.get('frequency', 0)})")
        return "\n".join(lines)
    
    def _format_emotional_spikes(self, spikes: list) -> str:
        if not spikes:
            return "No emotional spikes detected."
        
        lines = []
        for s in spikes:
            lines.append(f"- **{s.get('topic', 'N/A')}**: {s.get('sentiment', 0):.2f} ({s.get('intensity', 'unknown')})")
        return "\n".join(lines)
    
    def _format_contradictions(self, contradictions: list) -> str:
        if not contradictions:
            return "No contradictions detected."
        
        lines = []
        for c in contradictions:
            lines.append(f"- **{c.get('narrative', 'N/A')}** vs **{c.get('counter_narrative', 'N/A')}**")
        return "\n".join(lines)
    
    def _format_future_leaks(self, leaks: list) -> str:
        if not leaks:
            return "No future leak indicators detected."
        
        lines = []
        for l in leaks:
            lines.append(f"- **{l.get('indicator', 'N/A')}**: {l.get('confidence', 0):.2f} confidence ({l.get('possible_timeline', 'unknown')})")
        return "\n".join(lines)
