"""Markdown report generator - WebBot 2.0 format."""

import json
from datetime import datetime
from typing import Any, Dict


class MarkdownReporter:
    """Generate Markdown reports from WebBot 2.0 analysis results."""

    def __init__(self):
        self.template = """# Predictive Linguistics Report - WebBot 2.0
Generated: {timestamp}

## Summary
{summary}

---

## Temporal Anomalies (Time-Displacement)
{temporal_anomalies}

---

## Memetic Lifecycle Analysis
{memetic_lifecycle}

---

## Archetypes (Jungian)
{archetypes}

---

## Emerging Metaphors
{metaphors}

---

## Contradictions & Cognitive Dissonance
{contradictions}

---

## Future Leak Indicators
{future_leaks}

---

## Cross-Platform Patterns
{cross_platform}

---
*Generated by Predictive Linguistics WebBot 2.0 - Based on Original WebBot Methodology*
"""

    def generate(self, data: Dict[str, Any], search_term: str = "", limit: int = 0) -> str:
        """Generate Markdown report."""
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        search_info = f"**Search Term:** {search_term}" if search_term else ""
        if limit:
            search_info += f" | **Limit:** {limit}" if search_info else f"**Limit:** {limit}"

        summary = data.get("summary", "No summary available.")
        temporal_anomalies = self._format_temporal_anomalies(data.get("temporal_anomalies", []))
        memetic_lifecycle = self._format_memetic_lifecycle(data.get("memetic_lifecycle", []))
        archetypes = self._format_archetypes_webbot(data.get("archetypes", []))
        metaphors = self._format_metaphors(data.get("metaphors", []))
        contradictions = self._format_contradictions(data.get("contradictions", []))
        future_leaks = self._format_future_leaks(data.get("future_leaks", []))
        cross_platform = self._format_cross_platform(data.get("cross_platform_patterns", []))

        return self.template.format(
            timestamp=timestamp,
            summary=summary,
            temporal_anomalies=temporal_anomalies,
            memetic_lifecycle=memetic_lifecycle,
            archetypes=archetypes,
            metaphors=metaphors,
            contradictions=contradictions,
            future_leaks=future_leaks,
            cross_platform=cross_platform,
        )

    def _format_temporal_anomalies(self, anomalies: list) -> str:
        if not anomalies:
            return "No temporal anomalies detected."

        lines = []
        for a in anomalies:
            conf = a.get("confidence", 0)
            conf_emoji = "🔴" if conf > 0.7 else "🟡" if conf > 0.5 else "🟢"
            lines.append(
                f"- {conf_emoji} **{a.get('future_reference', 'N/A')}** ({a.get('match_type', 'unknown')}) - {a.get('platform', 'unknown')} platform | confidence: {conf:.2f}"
            )
            lines.append(f"  > {a.get('text', '')[:150]}...")
        return "\n".join(lines)

    def _format_memetic_lifecycle(self, lifecycle: list) -> str:
        if not lifecycle:
            return "No memetic lifecycle data available."

        stage_names = {
            1: "Awareness",
            2: "Excitement",
            3: "Momentum",
            4: "Critique",
            5: "Integration",
            6: "Nostalgia",
        }

        stage_emojis = {1: "🌱", 2: "🚀", 3: "📈", 4: "🔍", 5: "✅", 6: "📚"}

        lines = []
        for item in lifecycle:
            stage = item.get("stage", 1)
            emoji = stage_emojis.get(stage, "❓")
            lines.append(f"- {emoji} **{item.get('pattern', 'N/A')}**")
            lines.append(
                f"  - Stage {stage}: {item.get('stage_name', stage_names.get(stage, 'Unknown'))}"
            )
            lines.append(f"  - Evidence: {item.get('evidence', 'N/A')}")
        return "\n".join(lines)

    def _format_archetypes_webbot(self, archetypes: list) -> str:
        if not archetypes:
            return "No archetypes detected."

        archetype_emojis = {
            "The Catalyst": "⚡",
            "The Herald": "📯",
            "The Shapeshifter": "🎭",
            "The Shadow": "🌑",
            "The Wise Elder": "🦉",
            "The Trickester": "🃏",
            "The Innocent": "🌼",
            "The Warrior": "⚔️",
        }

        lines = []
        for a in archetypes:
            name = a.get("name", "Unknown")
            emoji = archetype_emojis.get(name, "🎭")
            lines.append(f"- {emoji} **{name}** (frequency: {a.get('frequency', 0)})")
            examples = a.get("examples", [])
            if examples:
                for ex in examples[:2]:
                    lines.append(f'  - "{ex}"')
        return "\n".join(lines)

    def _format_metaphors(self, metaphors: list) -> str:
        if not metaphors:
            return "No emerging metaphors detected."

        lines = []
        for m in metaphors:
            is_emerging = m.get("is_emerging", False)
            emoji = "🆕" if is_emerging else "📊"
            lines.append(
                f"- {emoji} **{m.get('term', 'N/A')}**: {m.get('context', '')} (spread: {m.get('spread_score', 0):.2f})"
            )
        return "\n".join(lines)

    def _format_contradictions(self, contradictions: list) -> str:
        if not contradictions:
            return "No contradictions detected."

        lines = []
        for c in contradictions:
            tension = c.get("tension_level", "low")
            emoji = "🔴" if tension == "high" else "🟡" if tension == "medium" else "🟢"
            lines.append(f"- {emoji} **{c.get('narrative', 'N/A')}**")
            lines.append(f"  ↔ vs: {c.get('counter_narrative', 'N/A')}")
            lines.append(f"  Tension: {tension}")
        return "\n".join(lines)

    def _format_future_leaks(self, leaks: list) -> str:
        if not leaks:
            return "No future leak indicators detected."

        lines = []
        for l in leaks:
            conf = l.get("confidence", 0)
            conf_emoji = "🔴" if conf > 0.7 else "🟡" if conf > 0.5 else "🟢"
            lines.append(f"- {conf_emoji} **{l.get('indicator', 'N/A')}**")
            lines.append(
                f"  - Confidence: {conf:.2f} | Timeline: {l.get('timeline', l.get('possible_timeline', 'unknown'))}"
            )
            evidence = l.get("supporting_evidence", [])
            if evidence:
                lines.append(f"  - Evidence: {', '.join(evidence[:2])}")
        return "\n".join(lines)

    def _format_cross_platform(self, patterns: list) -> str:
        if not patterns:
            return "No cross-platform patterns detected."

        lines = []
        for p in patterns:
            sync = p.get("synchronization", "unknown")
            emoji = "✅" if sync == "synchronized" else "🔄" if sync == "emerging" else "❓"
            platforms = ", ".join(p.get("platforms", []))
            lines.append(f"- {emoji} **{p.get('pattern', 'N/A')}**")
            lines.append(f"  - Platforms: {platforms}")
            lines.append(f"  - Sync: {sync}")
        return "\n".join(lines)
