"""Markdown report generator - WebBot 2.0 format."""

import json
from datetime import datetime
from typing import Any, Dict


class MarkdownReporter:
    """Generate Markdown reports from WebBot 2.0 analysis results."""

    def __init__(self):
        self.template = """# Predictive Linguistics Report - WebBot 2.0
Generated: {timestamp}

## Entities Detected
{entities}

---

## Prediction Timeframes
{timeframes}

---

## Detail Words (Unusual Context)
{detail_words}

---

## Summary
{summary}

---

## Temporal Anomalies (Time-Displacement)
{temporal_anomalies}

---

## Temporal Echoes
{temporal_echoes}

---

## Memetic Lifecycle Analysis
{memetic_lifecycle}

---

## Archetypes (Jungian)
{archetypes}

---

## Emerging Metaphors
{metaphors}

---

## Contradictions & Cognitive Dissonance
{contradictions}

---

## Future Leak Indicators
{future_leaks}

---

## Cross-Platform Patterns
{cross_platform}

---
*Generated by Predictive Linguistics WebBot 2.0 - Based on Original WebBot Methodology (clif high)*
"""

    def generate(self, data: Dict[str, Any], search_term: str = "", limit: int = 0) -> str:
        """Generate Markdown report."""
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        # Handle raw_analysis case - try to extract JSON from LLM response
        if "raw_analysis" in data and "error" in data:
            raw = data.get("raw_analysis", "")
            import re

            json_match = re.search(r"```json\s*(.*?)\s*```", raw, re.DOTALL)
            if json_match:
                try:
                    parsed = json.loads(json_match.group(1))
                    data = parsed
                except:
                    pass

        search_info = f"**Search Term:** {search_term}" if search_term else ""
        if limit:
            search_info += f" | **Limit:** {limit}" if search_info else f"**Limit:** {limit}"

        summary = data.get("summary", "No summary available.")
        temporal_anomalies = self._format_temporal_anomalies(data.get("temporal_anomalies", []))
        memetic_lifecycle = self._format_memetic_lifecycle(data.get("memetic_lifecycle", []))
        archetypes = self._format_archetypes_webbot(data.get("archetypes", []))
        metaphors = self._format_metaphors(data.get("metaphors", []))
        contradictions = self._format_contradictions(data.get("contradictions", []))
        future_leaks = self._format_future_leaks(data.get("future_leaks", []))
        cross_platform = self._format_cross_platform(data.get("cross_platform_patterns", []))

        # New fields
        entities = self._format_entities(data.get("entities", []))
        timeframes = self._format_timeframes(data.get("timeframes", []))
        detail_words = self._format_detail_words(data.get("detail_words", []))
        temporal_echoes = self._format_temporal_echoes(data.get("temporal_echoes", []))

        return self.template.format(
            timestamp=timestamp,
            entities=entities,
            timeframes=timeframes,
            detail_words=detail_words,
            summary=summary,
            temporal_anomalies=temporal_anomalies,
            temporal_echoes=temporal_echoes,
            memetic_lifecycle=memetic_lifecycle,
            archetypes=archetypes,
            metaphors=metaphors,
            contradictions=contradictions,
            future_leaks=future_leaks,
            cross_platform=cross_platform,
        )

    def _format_entities(self, entities: list) -> str:
        if not entities:
            return "No entity classification detected."
        lines = []
        for e in entities:
            weight = e.get("weight", 0)
            emoji = "🔴" if weight > 0.7 else "🟡" if weight > 0.4 else "🟢"
            lines.append(f"- {emoji} **{e.get('name', 'Unknown')}** (weight: {weight:.2f})")
            lines.append(f"  Key themes: {', '.join(e.get('key_themes', []))}")
        return "\n".join(lines)

    def _format_timeframes(self, timeframes: list) -> str:
        if not timeframes:
            return "No prediction timeframes identified."
        lines = []
        for t in timeframes:
            tf_type = t.get("type", "Unknown")
            label = t.get("label", "Unknown")
            conf = t.get("confidence", 0)
            emoji = "🔴" if conf > 0.7 else "🟡" if conf > 0.5 else "🟢"
            lines.append(f"- {emoji} **{tf_type}** ({label}) - confidence: {conf:.2f}")
            for ind in t.get("indicators", []):
                lines.append(f"  - {ind}")
        return "\n".join(lines)

    def _format_detail_words(self, detail_words: list) -> str:
        if not detail_words:
            return "No detail words detected."
        lines = []
        for w in detail_words:
            score = w.get("predictive_score", 0)
            emoji = "🔴" if score > 0.7 else "🟡" if score > 0.4 else "🟢"
            lines.append(f"- {emoji} **{w.get('word', 'Unknown')}**")
            lines.append(f"  Context: {w.get('unexpected_context', 'N/A')}")
            lines.append(
                f"  Timeline: {w.get('emergence_timeline', 'Unknown')} | Score: {score:.2f}"
            )
        return "\n".join(lines)

    def _format_temporal_echoes(self, echoes: list) -> str:
        if not echoes:
            return "No temporal echoes detected."
        lines = []
        for e in echoes:
            change = e.get("intensity_change", "unknown")
            emoji = "📈" if change == "increasing" else "📉" if change == "decreasing" else "➡️"
            lines.append(f"- {emoji} **{e.get('meme', 'Unknown')}**")
            lines.append(f"  Previous: {e.get('previous_occurrence', 'N/A')}")
            lines.append(f"  Current: {e.get('current_occurrence', 'N/A')}")
            lines.append(f"  Intensity: {change}")
        return "\n".join(lines)

    def _format_temporal_anomalies(self, anomalies: list) -> str:
        if not anomalies:
            return "No temporal anomalies detected."

        lines = []
        for a in anomalies:
            conf = a.get("confidence", 0)
            conf_emoji = "🔴" if conf > 0.7 else "🟡" if conf > 0.5 else "🟢"
            lines.append(
                f"- {conf_emoji} **{a.get('future_reference', 'N/A')}** ({a.get('match_type', 'unknown')}) - {a.get('platform', 'unknown')} platform | confidence: {conf:.2f}"
            )
            lines.append(f"  > {a.get('text', '')[:150]}...")
        return "\n".join(lines)

    def _format_memetic_lifecycle(self, lifecycle: list) -> str:
        if not lifecycle:
            return "No memetic lifecycle data available."

        stage_names = {
            1: "Awareness",
            2: "Excitement",
            3: "Momentum",
            4: "Critique",
            5: "Integration",
            6: "Nostalgia",
        }

        stage_emojis = {1: "🌱", 2: "🚀", 3: "📈", 4: "🔍", 5: "✅", 6: "📚"}

        lines = []
        for item in lifecycle:
            stage = item.get("stage", 1)
            emoji = stage_emojis.get(stage, "❓")
            lines.append(f"- {emoji} **{item.get('pattern', 'N/A')}**")
            lines.append(
                f"  - Stage {stage}: {item.get('stage_name', stage_names.get(stage, 'Unknown'))}"
            )
            lines.append(f"  - Evidence: {item.get('evidence', 'N/A')}")
        return "\n".join(lines)

    def _format_archetypes_webbot(self, archetypes: list) -> str:
        if not archetypes:
            return "No archetypes detected."

        archetype_emojis = {
            "The Catalyst": "⚡",
            "The Herald": "📯",
            "The Shapeshifter": "🎭",
            "The Shadow": "🌑",
            "The Wise Elder": "🦉",
            "The Trickester": "🃏",
            "The Innocent": "🌼",
            "The Warrior": "⚔️",
        }

        lines = []
        for a in archetypes:
            name = a.get("name", "Unknown")
            emoji = archetype_emojis.get(name, "🎭")
            lines.append(f"- {emoji} **{name}** (frequency: {a.get('frequency', 0)})")
            examples = a.get("examples", [])
            if examples:
                for ex in examples[:2]:
                    lines.append(f'  - "{ex}"')
        return "\n".join(lines)

    def _format_metaphors(self, metaphors: list) -> str:
        if not metaphors:
            return "No emerging metaphors detected."

        lines = []
        for m in metaphors:
            is_emerging = m.get("is_emerging", False)
            emoji = "🆕" if is_emerging else "📊"
            lines.append(
                f"- {emoji} **{m.get('term', 'N/A')}**: {m.get('context', '')} (spread: {m.get('spread_score', 0):.2f})"
            )
        return "\n".join(lines)

    def _format_contradictions(self, contradictions: list) -> str:
        if not contradictions:
            return "No contradictions detected."

        lines = []
        for c in contradictions:
            tension = c.get("tension_level", "low")
            emoji = "🔴" if tension == "high" else "🟡" if tension == "medium" else "🟢"
            lines.append(f"- {emoji} **{c.get('narrative', 'N/A')}**")
            lines.append(f"  ↔ vs: {c.get('counter_narrative', 'N/A')}")
            lines.append(f"  Tension: {tension}")
        return "\n".join(lines)

    def _format_future_leaks(self, leaks: list) -> str:
        if not leaks:
            return "No future leak indicators detected."

        lines = []
        for l in leaks:
            conf = l.get("confidence", 0)
            conf_emoji = "🔴" if conf > 0.7 else "🟡" if conf > 0.5 else "🟢"
            lines.append(f"- {conf_emoji} **{l.get('indicator', 'N/A')}**")
            lines.append(
                f"  - Confidence: {conf:.2f} | Timeline: {l.get('timeline', l.get('possible_timeline', 'unknown'))}"
            )
            evidence = l.get("supporting_evidence", [])
            if evidence:
                lines.append(f"  - Evidence: {', '.join(evidence[:2])}")
        return "\n".join(lines)

    def _format_cross_platform(self, patterns: list) -> str:
        if not patterns:
            return "No cross-platform patterns detected."

        lines = []
        for p in patterns:
            sync = p.get("synchronization", "unknown")
            emoji = "✅" if sync == "synchronized" else "🔄" if sync == "emerging" else "❓"
            platforms = ", ".join(p.get("platforms", []))
            lines.append(f"- {emoji} **{p.get('pattern', 'N/A')}**")
            lines.append(f"  - Platforms: {platforms}")
            lines.append(f"  - Sync: {sync}")
        return "\n".join(lines)
